import type { CercleQuestion, Question } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    mod: "memory",
    modLabel: "🧠 Piège de la mémoire",
    question: "Regarde bien cette image pendant 10 secondes. Mémorise ABSOLUMENT TOUT ce que tu vois !",
    visual: {
      type: "scene-voiture",
      figures: "🚗💨",
      timer: "⏱ 10 sec",
      scene: "Avenue tropicale. Palmiers, bus jaune, avion dans le ciel bleu, mer au loin. Une voiture de sport bleue décapotable roule à vive allure.",
      image: "/images/jeu-stereotypes/scene-memoire-avenue.png",
      imageAlt: "Avenue tropicale avec palmiers, bus jaune, avion, parapente, mer et voiture bleue décapotable",
    },
    opts: [{ e: "👀", l: "J'ai bien regardé !" }],
    isPoll: true,
    colClass: "col1",
    fb: {
      type: "info",
      lbl: "⏭ Les questions pièges arrivent...",
      txt: "Ton cerveau vient d'enregistrer la scène. Mais a-t-il retenu ce qui était là... ou ce qu'il s'attendait à voir ? La vraie question arrive dans quelques instants !",
    },
  },
  {
    id: 2,
    mod: "chiffres",
    modLabel: "📊 Le saviez-vous ?",
    question: "En France en 2024, quel est le taux d'emploi des femmes de 15 à 64 ans ?",
    visual: {
      type: "scene-pilote",
      figures: "📊",
      scene: "Source : INSEE 2024 — données officielles sur le marché du travail en France.",
      image: "/images/jeu-stereotypes/femme-pilote-avion.png",
      imageAlt: "Une femme pilote en uniforme devant l'escalier d'un avion au coucher du soleil",
      secondImage: "/images/jeu-stereotypes/homme-pilote-avion.png",
      secondImageAlt: "Un homme pilote en uniforme devant l'escalier d'un avion au coucher du soleil",
    },
    opts: [
      { e: "📊", l: "Environ 45%" },
      { e: "📊", l: "Environ 55%" },
      { e: "📊", l: "Environ 66%" },
      { e: "📊", l: "Environ 80%" },
    ],
    isPoll: false,
    correct: 2,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "💥 66,2% !",
      txt: "66,2% des femmes de 15-64 ans travaillent en France, contre 71,5% des hommes. Un écart de 5 points qui persiste encore — et l'écart de salaire atteint 21,8% dans le secteur privé.",
    },
  },
  {
    id: 3,
    mod: "images",
    modLabel: "🖼 Regarde bien",
    question: "Tu vois cette scène. À quel métier penses-tu instinctivement ?",
    visual: {
      type: "scene-office",
      figures: "👔💻📞",
      label: "Scène A",
      scene: "Une personne en chemise blanche, au bureau. Téléphone à l'oreille, stylo en main. Post-its colorés derrière.",
      image: "/images/jeu-stereotypes/scene-bureau-homme.png",
      imageAlt: "Un homme en chemise blanche au téléphone, assis à un bureau avec un stylo en main",
    },
    opts: [
      { e: "💼", l: "Directeur·trice" },
      { e: "📞", l: "Téléconseiller·ère" },
      { e: "🧑‍💻", l: "Informaticien·ne" },
      { e: "📊", l: "Commercial·e" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "info",
      lbl: "🤔 Mémorise ta réponse...",
      txt: "Quelle personne imaginais-tu ? Un homme ou une femme ? Cette même scène va revenir plus tard — observe si ta réponse change !",
    },
  },
  {
    id: 4,
    mod: "maison",
    modLabel: "🏠 À la maison",
    question: "Chez toi, qui cuisine le plus souvent ?",
    visual: {
      type: "scene-maison",
      figures: "🍳👨‍👩‍👧",
      scene: "Une cuisine familiale un soir de semaine. Odeur de sauce tomate. Les enfants ont faim.",
    },
    opts: [
      { e: "👩", l: "Plutôt ma mère" },
      { e: "👨", l: "Plutôt mon père" },
      { e: "🤝", l: "Les deux pareil" },
      { e: "🤷", l: "Ça dépend" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "📊 Les chiffres sont clairs",
      txt: "En France, les femmes passent en moyenne 3h26 par jour aux tâches domestiques contre 2h pour les hommes — même quand les deux travaillent à temps plein. C'est la charge mentale.",
    },
  },
  {
    id: 5,
    mod: "vrfx",
    modLabel: "❓ Vrai ou Faux ?",
    question: "Les filles sont moins douées en mathématiques que les garçons.",
    opts: [{ e: "✅", l: "Vrai" }, { e: "❌", l: "Faux" }],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "insight",
      lbl: "💡 FAUX !",
      txt: "Les filles ont de meilleures notes en maths que les garçons en primaire ! L'écart s'inverse au collège à cause des stéréotypes, pas de la biologie. Pourtant seulement 27% des ingénieurs sont des femmes.",
    },
  },
  {
    id: 6,
    mod: "images",
    modLabel: "🖼 Regarde bien",
    question: "Trois personnes en tenue chirurgicale souriantes. Quel est leur rôle selon toi ?",
    visual: {
      type: "scene-medical",
      figures: "👩‍⚕️👩‍⚕️👩‍⚕️",
      label: "Scène B",
      scene: "Trois femmes souriantes, tenue chirurgicale bleue, bonnet de bloc. Bloc opératoire en arrière-plan.",
      image: "/images/jeu-stereotypes/scene-chirurgiennes.png",
      imageAlt: "Trois femmes souriantes en tenue chirurgicale bleue dans un bloc opératoire",
    },
    opts: [
      { e: "🔪", l: "Chirurgiennes" },
      { e: "💉", l: "Anesthésistes" },
      { e: "🩺", l: "Médecins" },
      { e: "🧑‍⚕️", l: "Infirmières" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "⚠️ Le biais médical",
      txt: "On imagine spontanément les femmes en tenue médicale comme infirmières et les hommes comme chirurgiens — même contexte identique. Les femmes représentent pourtant plus de 60% des étudiants en médecine !",
    },
  },
  {
    id: 7,
    mod: "emotions",
    modLabel: "💭 Émotions & Genre",
    question: "Un garçon de 12 ans pleure en classe après une mauvaise note. Qu'est-ce que tu penses de lui ?",
    opts: [
      { e: "💪", l: "Il est courageux" },
      { e: "😅", l: "C'est gênant" },
      { e: "😢", l: "C'est normal" },
      { e: "🤔", l: "Ça dépend" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "💔 La prison émotionnelle",
      txt: "Les garçons apprennent à supprimer leurs larmes vers 5 ans sous pression sociale. Les hommes ont 3x plus de risques de suicide que les femmes — en partie parce qu'ils ne peuvent pas exprimer leur détresse.",
    },
  },
  {
    id: 8,
    mod: "memory",
    modLabel: "🧠 Piège de la mémoire",
    question: "Souviens-toi de l'image du début. Quelle était la couleur du bus ?",
    opts: [
      { e: "🟡", l: "Jaune" },
      { e: "🔴", l: "Rouge" },
      { e: "🔵", l: "Bleu" },
      { e: "⬜", l: "Blanc" },
    ],
    isPoll: false,
    correct: 0,
    colClass: "",
    fb: {
      type: "info",
      lbl: "✅ Jaune ! Bien.",
      txt: "Le bus était jaune. Ton cerveau commence à se fatiguer avec tous ces détails... et c'est exactement le but. La vraie question piège arrive !",
    },
  },
  {
    id: 9,
    mod: "memory",
    modLabel: "🧠 Piège de la mémoire",
    question: "Dernière question sur cette image : qui conduisait la voiture de sport bleue ?",
    opts: [
      { e: "👨", l: "Un homme" },
      { e: "👩", l: "Une femme" },
      { e: "🤷", l: "Je ne sais plus" },
    ],
    isPoll: false,
    correct: 1,
    colClass: "col3",
    fb: {
      type: "shock",
      lbl: "💥 C'était une femme !",
      txt: "La majorité des gens répondent 'un homme' — même ceux qui se souviennent de la plaque d'immatriculation ! Le cerveau remplace ce qu'il voit par ce qu'il s'attend à voir. C'est exactement comme ça que les biais fonctionnent.",
    },
  },
  {
    id: 10,
    mod: "bienveillant",
    modLabel: "🎭 Compliment ou piège ?",
    question: "\"Tu conduis vraiment bien pour une fille !\" — c'est quoi cette phrase ?",
    opts: [
      { e: "😊", l: "Un gentil compliment" },
      { e: "😬", l: "Du sexisme" },
      { e: "🤔", l: "Ça dépend du contexte" },
    ],
    isPoll: false,
    correct: 1,
    colClass: "col3",
    fb: {
      type: "shock",
      lbl: "⚠️ Sexisme bienveillant",
      txt: "Cette phrase semble gentille mais sous-entend que les femmes conduisent mal par défaut. C'est du sexisme bienveillant — il flatte en enfermant. Les femmes causent statistiquement moins d'accidents graves que les hommes.",
    },
  },
  {
    id: 11,
    mod: "maison",
    modLabel: "🏠 À la maison",
    question: "Chez toi, qui répare les choses quand elles sont cassées ?",
    visual: {
      type: "scene-chantier",
      figures: "🔨🔧🪛",
      scene: "L'étagère IKEA est par terre. La notice est introuvable. Il est 21h.",
    },
    opts: [
      { e: "👩", l: "Plutôt ma mère" },
      { e: "👨", l: "Plutôt mon père" },
      { e: "🤝", l: "Les deux pareil" },
      { e: "📞", l: "On appelle quelqu'un" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "info",
      lbl: "🔨 Le bricolage, c'est appris !",
      txt: "Les femmes bricolent autant que les hommes quand elles ont été encouragées dès l'enfance. Mais les garçons reçoivent outils et Lego, les filles des dinettes. Pas une question de talent — d'entraînement !",
    },
  },
  {
    id: 12,
    mod: "vrfx",
    modLabel: "❓ Vrai ou Faux ?",
    question: "L'intuition est un don naturel féminin — les femmes en ont naturellement plus.",
    opts: [{ e: "✅", l: "Vrai" }, { e: "❌", l: "Faux" }],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "⚠️ FAUX — c'est un piège ancien",
      txt: "L'intuition est un mécanisme cérébral universel. Depuis l'Antiquité, on a refusé aux femmes la capacité de 'raisonner' et on leur a donné 'l'intuition' à la place. Une façon élégante de les exclure du pouvoir de décision pendant 2000 ans.",
    },
  },
  {
    id: 13,
    mod: "images",
    modLabel: "🖼 Même question, image différente",
    question: "Même question qu'à la scène B. Trois personnes en tenue chirurgicale — quel est leur rôle ?",
    visual: {
      type: "scene-medical",
      figures: "👨‍⚕️👨‍⚕️👨‍⚕️",
      label: "Scène C",
      scene: "Trois hommes souriants, tenue chirurgicale bleue, bonnet de bloc. Même bloc opératoire.",
      image: "/images/jeu-stereotypes/scene-chirurgiens.png",
      imageAlt: "Trois hommes souriants en tenue chirurgicale bleue dans un bloc opératoire",
    },
    opts: [
      { e: "🔪", l: "Chirurgiens" },
      { e: "💉", l: "Anesthésistes" },
      { e: "🩺", l: "Médecins" },
      { e: "🧑‍⚕️", l: "Infirmiers" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "insight",
      lbl: "💡 Tu vois la différence ?",
      txt: "As-tu répondu différemment qu'à la scène B avec les femmes ? Si oui, c'est un biais inconscient — tu n'es pas seul(e), c'est le cas de la majorité des gens. La prise de conscience, c'est déjà changer les choses !",
    },
  },
  {
    id: 14,
    mod: "vrfx",
    modLabel: "❓ Vrai ou Faux ?",
    question: "Les femmes sont naturellement plus bavardes que les hommes.",
    opts: [{ e: "✅", l: "Vrai" }, { e: "❌", l: "Faux" }],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "insight",
      lbl: "💡 FAUX !",
      txt: "Dans les espaces publics et professionnels, les hommes parlent davantage. Dans les réunions mixtes, les hommes occupent en moyenne 75% du temps de parole. Et les femmes qui parlent autant sont jugées 'dominantes'.",
    },
  },
  {
    id: 15,
    mod: "images",
    modLabel: "🖼 Même scène, personne différente",
    question: "Retour sur la scène du bureau. Cette fois avec une femme. Même question — quel métier ?",
    visual: {
      type: "scene-office",
      figures: "👩‍💼💻📞",
      label: "Scène D",
      scene: "Une femme en chemise blanche, au bureau. Téléphone à l'oreille, stylo en main. Post-its colorés derrière. Exactement la même scène qu'avant.",
      image: "/images/jeu-stereotypes/scene-bureau-femme.png",
      imageAlt: "Une femme en chemise blanche au téléphone, assise à un bureau avec un stylo en main",
    },
    opts: [
      { e: "💼", l: "Directrice" },
      { e: "📞", l: "Téléconseillère" },
      { e: "🧑‍💻", l: "Informaticienne" },
      { e: "📊", l: "Commerciale" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "🤔 Compare avec la scène A",
      txt: "As-tu choisi le même métier qu'à la scène A avec l'homme ? Si ce n'est pas le cas — c'est un biais inconscient. Les deux personnes font exactement la même chose. C'est ça le cœur du problème.",
    },
  },
  {
    id: 16,
    mod: "bienveillant",
    modLabel: "🎭 Compliment ou piège ?",
    question: "\"Les femmes sont tellement plus douces avec les enfants.\" — c'est quoi cette phrase ?",
    opts: [
      { e: "😊", l: "Un fait naturel" },
      { e: "😬", l: "Un stéréotype" },
      { e: "🤔", l: "Ça dépend" },
    ],
    isPoll: false,
    correct: 1,
    colClass: "col3",
    fb: {
      type: "shock",
      lbl: "⚠️ Sexisme bienveillant encore !",
      txt: "Cette phrase semble valorisante mais enferme les femmes dans le rôle de soignante et exclut les hommes de la parentalité. C'est comme ça que les inégalités domestiques se perpétuent de génération en génération.",
    },
  },
  {
    id: 17,
    mod: "emotions",
    modLabel: "💭 Liberté d'être soi",
    question: "Un garçon de 14 ans fait de la danse classique. Une fille fait de la boxe. Lequel va être le plus jugé ?",
    visual: {
      type: "scene-sport",
      figures: "🩰🥊",
      scene: "Deux couloirs différents. Deux passions. Deux regards de la société.",
    },
    opts: [
      { e: "🩰", l: "Le danseur" },
      { e: "🥊", l: "La boxeuse" },
      { e: "⚖️", l: "Les deux pareil" },
      { e: "🤷", l: "Ni l'un ni l'autre" },
    ],
    isPoll: true,
    colClass: "",
    fb: {
      type: "insight",
      lbl: "💡 Les deux sont jugés !",
      txt: "Le garçon danseur et la fille boxeuse sont tous les deux punis pour avoir simplement été eux-mêmes. Les stéréotypes n'emprisonnent pas que les filles — ils emprisonnent tout le monde. La liberté d'être soi, c'est pour tous.",
    },
  },
  {
    id: 18,
    mod: "vrfx",
    modLabel: "❓ Vrai ou Faux ?",
    question: "Les jouets roses pour filles et bleus pour garçons ont toujours existé.",
    opts: [{ e: "✅", l: "Vrai, c'est naturel" }, { e: "❌", l: "Faux, c'est récent" }],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "💥 FAUX — c'est du marketing !",
      txt: "Les jouets genrés rose/bleu n'existent que depuis les années 70-80. Inventés par les fabricants pour vendre deux fois plus — si chaque sexe a ses jouets, les frères et sœurs ne peuvent pas se les partager !",
    },
  },
  {
    id: 19,
    mod: "maison",
    modLabel: "🏠 À la maison",
    question: "Dans une émission TV, on a demandé à des enfants : qu'est-ce que papa fait que maman ne fait pas ? Quelle était leur réponse ?",
    opts: [
      { e: "🔨", l: "Le bricolage" },
      { e: "😴", l: "La sieste" },
      { e: "🚗", l: "Conduire" },
      { e: "💼", l: "Travailler" },
    ],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "insight",
      lbl: "😴 La sieste !",
      txt: "Les enfants ont répondu : la sieste ! Papa se repose sans culpabilité. Maman ne s'arrête jamais vraiment. Un enfant de 7 ans vient d'expliquer la charge mentale mieux que n'importe quel sociologue.",
    },
  },
  {
    id: 20,
    mod: "chiffres",
    modLabel: "📊 Le paradoxe",
    question: "Les filles ont de meilleures notes que les garçons au lycée. Et pourtant dans les filières d'ingénieurs...",
    opts: [
      { e: "📈", l: "Elles sont majoritaires" },
      { e: "📉", l: "Elles s'autocensurent" },
      { e: "🤝", l: "C'est équilibré" },
      { e: "🤷", l: "Je ne sais pas" },
    ],
    isPoll: false,
    correct: 1,
    colClass: "",
    fb: {
      type: "shock",
      lbl: "💔 L'autocensure",
      txt: "Malgré de meilleures notes, les filles s'orientent moins vers les filières scientifiques valorisées. Pas par manque de capacités — par manque de confiance, construit par des années de stéréotypes. C'est exactement ce qu'Elles Bougent combat.",
    },
  },
];

export const cercleQs: CercleQuestion[] = [
  {
    q: "Qui parmi vous a déjà fait une bêtise ?",
    short: "Déjà fait\nune bêtise ?",
    type: "all",
    title: "Tout le monde ! 😂",
    body: "Les bêtises n'ont pas de genre. Et pourtant on punit différemment les garçons et les filles pour les mêmes actes dès le plus jeune âge.",
  },
  {
    q: "Qui parmi vous a déjà eu peur de rentrer seule la nuit ?",
    short: "Peur de rentrer\nseule la nuit ?",
    type: "girls",
    title: "Surtout les filles. 😶",
    body: "Les garçons rentrent seuls sans y penser. Les filles planifient leur trajet, partagent leur position, gardent le téléphone en main. Cette inégalité est réelle et quotidienne.",
  },
  {
    q: "Qui parmi vous a déjà vécu un grand chagrin d'amour ?",
    short: "Un grand\nchagrin d'amour ?",
    type: "all",
    title: "Tout le monde. ❤️",
    body: "La douleur émotionnelle est universelle. Et pourtant on apprend aux garçons à la cacher et aux filles qu'elles sont 'trop sensibles'. Les deux sont enfermés.",
  },
  {
    q: "Qui parmi vous s'est déjà autocensurée dans un choix d'orientation par peur du regard des autres ?",
    short: "Autocensurée\ndans ton orientation ?",
    type: "girls",
    title: "Beaucoup d'entre vous. 💔",
    body: "Ce n'est pas toi le problème — c'est le regard de la société. Les stéréotypes te font douter de toi alors que tu as les capacités. C'est exactement ce qu'on veut changer aujourd'hui.",
  },
  {
    q: "Qui parmi vous a déjà entendu 'c'est un métier de garçon' ou 'c'est pas pour les filles' ?",
    short: "'C'est un métier\nde garçon' ?",
    type: "all",
    title: "Presque toutes. 😤",
    body: "Ces phrases semblent anodines mais orientent des vies entières. Elles sont à l'origine de filières déséquilibrées, de carrières abandonnées, de vocations étouffées.",
  },
  {
    q: "Qui s'est déjà imaginé vivre dans la peau d'un garçon — rentrer seule la nuit, être prise au sérieux d'emblée ?",
    short: "Dans la peau\nd'un garçon ?",
    type: "girls",
    title: "Beaucoup de filles. 🤔",
    body: "Les filles imaginent la vie des garçons parce qu'elles ont des raisons concrètes de le faire. C'est le privilège invisible — celui qu'on ne voit pas parce qu'on ne manque de rien.",
  },
  {
    q: "Qui parmi vous a besoin de tendresse ?",
    short: "Besoin de\ntendresse ?",
    type: "all",
    title: "Tout le monde. 💛",
    body: "On est toutes pareilles là-dedans. Les stéréotypes nous ont juste appris à l'exprimer — ou à le cacher — différemment. C'est ça qu'on veut changer. La liberté d'être soi, c'est pour tout le monde.",
  },
];
